"""INR auto-accessories agency-managed brand (seed manifest). Deterministic from the seed string —
demo-grade: ~40 SKUs with realistic categories, per-SKU COGS/fees, inventory tuned so the stockout
rule fires, an ACOS spread crossing break-even, a designated hero SKU for the undercut injector, and
mixed connection states (one expired). Curves/report are generated by realify.agency.sandbox."""

SPEC = {
    "seed": "realify-sandbox-auto_in-v1",
    "currency": "INR",
    "hq_country": "IN",
    "sku_count": 40,
    "categories": ["Car cover", "Dashcam", "Phone mount", "Seat organizer", "Tyre inflator",
                   "LED kit", "Floor mats", "Charger"],
    "prices": [499, 899, 1299, 1999, 2499, 3299],
    "hero_sku": "SB-000",                      # undercut injector targets the hero
    "festival_ramp": True,                     # INR brand: festival demand ramp on the 90d curve
    "connections": [("amazon", "connected"), ("amazon_ads", "expired"), ("shopify", "connected")],
    "envelope": "Full Operate",
    "fx_inr_ppm": 83_500_000,
}
